Gui:
    Game Name: "J League Winning Eleven 2007 Club Championship"

option_file_data:
    Game Identifier : "BISLPM-66810JW11OPT"
    ENCRYPTED : True    
    OF_BYTE_LENGTH : 1002496
    OF_BLOCK : [
        12,
        5144,
        9544,
        16740,
        39568,
        592332,
        669788,
        689028,
        827656,
        983292,
    ]
    OF_BLOCK_SIZE : [
        4868,
        1268,
        7180,
        22816,
        551924,
        77440,
        19228,
        138616,
        155624,
        18784,
    ]

Player:
    First Shop : 4100
    First ML Youth : 4260
    First ML Old : 4437
    First Unused : 4447

Club:
    Size : 92
    Max Abbr Name Size : 10
    First Emblem : 356
    First Club Emblem : 120
    J League Extra Teams : 46 # Only for J League games, for PES or WE set it to zero

Stadiums:
    Total : 62
    Max Lenght : 61

Leagues:
    Total : 39

Kits:
    Nation Kit Data Size : 0
    Club Kit Data Size : 552

Shop:
    Points Offset : 5216
    Has Background Selector : True
    Total Backgrounds : 63

NATIONS : [
    "Japan",
    "England",
    "France",
    "Italy",
    "Netherlands",
    "Spain",
    "Austria",
    "Belgium",
    "Czech",
    "Germany",
    "Greece",
    "Portugal",
    "Scotland",
    "Turkey",
    "Ukraine",
    "Mexico",
    "Argentina",
    "Brazil",
    "Kuwait",
    "UAE",
    "Qatar",
    "Iraq",
    "Uzbekistan",
    "Saudi Arabia",
    "Iran",
    "Syria",
    "Australia",
    "China",
    "Indonesia",
    "Thailand",
    "Korea",
    "Vietnam",
    "Costa Rica",
    "United States",
    "New Zealand",
    "Papua New Guinea",
    "Nigeria",
    "South Africa",
    "Algeria",
    "Albania",
    "Armenia",
    "Azerbaijan",
    "Belarus",
    "Bosnia-Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Denmark",
    "Estonia",
    "Faroe Islands",
    "Finland",
    "Georgia",
    "Hungary",
    "Iceland",
    "Ireland",
    "Israel",
    "Kazakhstan",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Macedonia",
    "Moldova",
    "Montenegro",
    "Northern Ireland",
    "Norway",
    "Poland",
    "Romania",
    "Russia",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Switzerland",
    "Yugoslavia",
    "Wales",
    "Angola",
    "Benin",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Cape Verde",
    "Republic of the Congo",
    "Cote d'Ivoire",
    "Democratic Republic of the Congo",
    "Egypt",
    "Equatorial Guinea",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Liberia",
    "Libya",
    "Mali",
    "Morocco",
    "Mozambique",
    "Senegal",
    "Sierra Leone",
    "Togo",
    "Tunisia",
    "Zambia",
    "Zimbabwe",
    "Canada",
    "Grenada",
    "Guadeloupe",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Martinique",
    "Netherlands Antilles",
    "Panama",
    "Republic of Trinidad and Tobago",
    "Bolivia",
    "Chile",
    "Columbia",
    "Ecuador",
    "Paraguay",
    "Peru",
    "Uruguay",
    "Venezuela",
    "Bahrain",
    "north korea",
    "Oman",
    "Free Nationality",
]