Gui:
    Game Name: "J League Winning Eleven 2009 Club Championship"

option_file_data:
    Game Identifier : "BISLPM-551822009OPT"
    ENCRYPTED : True    
    OF_BYTE_LENGTH : 1024000
    OF_BLOCK : [
        12,
        5144,
        9544,
        16976,
        39804,
        613524,
        690636,
        710612,
        848688,
        1004324,
    ]
    OF_BLOCK_SIZE : [
        4868,
        1268,
        7420,
        22816,
        572880,
        77100,
        19964,
        138064,
        155624,
        19428,
    ]

Player:
    First Shop : 1
    First ML Youth : 1
    First ML Old : 1
    First Unused : 4616

Club:
    Size : 92
    Max Abbr Name Size : 10
    First Emblem : 356
    First Club Emblem : 120
    J League Extra Teams : 55 # Only for J League games, for PES or WE set it to zero

Stadiums:
    Total : 55
    Max Lenght : 73

Leagues:
    Total : 39

Kits:
    Nation Kit Data Size : 0
    Club Kit Data Size : 552

Shop:
    Points Offset : 5216
    Has Background Selector : True
    Total Backgrounds : 63

NATIONS : [
    "Japan",
    "England",
    "France",
    "Italy",
    "Netherlands",
    "Spain",
    "Belgium",
    "Greece",
    "Portugal",
    "Scotland",
    "Serbia",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "Argentina",
    "Brazil",
    "Australia",
    "China",
    "Korea",
    "Indonesia",
    "Singapore",
    "Iran",
    "Qatar",
    "Saudi Arabia",
    "UAE",
    "Uzbekistan",
    "Costa Rica",
    "Mexico",
    "United States",
    "New Zealand",
    "Papua New Guinea",
    "Nigeria",
    "South Africa",
    "Algeria",
    "Albania",
    "Andorra",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Bosnia-Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech",
    "Denmark",
    "Estonia",
    "Faroe Islands",
    "Finland",
    "Georgia",
    "Germany",
    "Hungary",
    "Iceland",
    "Ireland",
    "Israel",
    "Kazakhstan",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Moldova",
    "Montenegro",
    "Northern Ireland",
    "Norway",
    "Poland",
    "Romania",
    "Russia",
    "San Marino",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Wales",
    "Yugoslavia",
    "Angola",
    "Benin",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Cape Verde",
    "Central Africa",
    "Chad",
    "Republic of the Congo",
    "Cote d'Ivoire",
    "Democratic Republic of the Congo",
    "Egypt",
    "Equatorial Guinea",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Liberia",
    "Libya",
    "Mali",
    "Morocco",
    "Mozambique",
    "Rwanda",
    "Senegal",
    "Sierra Leone",
    "Togo",
    "Tunisia",
    "Zambia",
    "Zimbabwe",
    "Barbados",
    "Canada",
    "Grenada",
    "Guadeloupe",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Martinique",
    "Netherlands Antilles",
    "Panama",
    "Republic of Trinidad and Tobago",
    "Bolivia",
    "Chile",
    "Columbia",
    "Ecuador",
    "Paraguay",
    "Peru",
    "Uruguay",
    "Venezuela",
    "Bahrain",
    "Iraq",
    "Kuwait",
    "Malaysia",
    "north korea",
    "Oman",
    "Syria",
    "Thailand",
    "Vietnam",
    "Solomon Islands",
    "Free Nationality",
]