Gui:
    Game Name: "J League Winning Eleven 2010 Club Championship"

option_file_data:
    Game Identifier : "BISLPM-55262JXLLOPT"
    ENCRYPTED : True    
    OF_BYTE_LENGTH : 1038336
    OF_BLOCK : [
        12,
        5144,
        10344,
        17776,
        40604,
        614324,
        691436,
        711412,
        862448,
        1018084,
    ]
    OF_BLOCK_SIZE : [
        4868,
        1268,
        7420,
        22816,
        572880,
        77100,
        19964,
        151024,
        155624,
        19428,
    ]

Player:
    First Shop : 1
    First ML Youth : 1
    First ML Old : 1
    First Unused : 4610

Club:
    Size : 92
    Max Abbr Name Size : 10
    First Emblem : 356
    First Club Emblem : 120
    J League Extra Teams : 55 # Only for J League games, for PES or WE set it to zero

Stadiums:
    Total : 55
    Max Lenght : 73

Leagues:
    Total : 39

Kits:
    Nation Kit Data Size : 0
    Club Kit Data Size : 632

Shop:
    Points Offset : 5216
    Has Background Selector : False
    Total Backgrounds : 0
NATIONS : [
    "Japan",
    "England",
    "France",
    "Italy",
    "Netherlands",
    "Spain",
    "Croatia",
    "Greece",
    "Portugal",
    "Romania",
    "Scotland",
    "Serbia",
    "Turkey",
    "Ukraine",
    "Argentina",
    "Brazil",
    "Australia",
    "China",
    "Korea",
    "Indonesia",
    "Singapore",
    "Iran",
    "Qatar",
    "Saudi Arabia",
    "UAE",
    "Uzbekistan",
    "Costa Rica",
    "Mexico",
    "United States",
    "New Zealand",
    "Papua New Guinea",
    "Nigeria",
    "South Africa",
    "Algeria",
    "Albania",
    "Andorra",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Belgium",
    "Bosnia-Herzegovina",
    "Bulgaria",
    "Cyprus",
    "Czech",
    "Denmark",
    "Estonia",
    "Faroe Islands",
    "Finland",
    "Georgia",
    "Germany",
    "Hungary",
    "Iceland",
    "Ireland",
    "Israel",
    "Kazakhstan",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Northern Ireland",
    "Norway",
    "Poland",
    "Russia",
    "San Marino",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Switzerland",
    "Tajikistan",
    "Turkmenistan",
    "Wales",
    "Yugoslavia",
    "Angola",
    "Benin",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Cape Verde",
    "Central Africa",
    "Republic of the Congo",
    "Cote d'Ivoire",
    "Democratic Republic of the Congo",
    "Egypt",
    "Equatorial Guinea",
    "Gabon",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Liberia",
    "Libya",
    "Madagascar",
    "Mali",
    "Morocco",
    "Mozambique",
    "Niger",
    "Senegal",
    "Sierra Leone",
    "Togo",
    "Tunisia",
    "Zambia",
    "Zimbabwe",
    "Aruba",
    "Barbados",
    "Canada",
    "Grenada",
    "Guadeloupe",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Martinique",
    "Netherlands Antilles",
    "Republic of Trinidad and Tobago",
    "Bolivia",
    "Chile",
    "Columbia",
    "Ecuador",
    "Paraguay",
    "Peru",
    "Uruguay",
    "Venezuela",
    "Iraq",
    "Kuwait",
    "Lebanon",
    "north korea",
    "Oman",
    "Philippines",
    "Syria",
    "Thailand",
    "Free Nationality",
]