Gui:
    Game Name: "J League Winning Eleven 2008 Club Championship"

option_file_data:
    Game Identifier : "BISLPM-55033JW12OPT"
    ENCRYPTED : True    
    OF_BYTE_LENGTH : 1021952
    OF_BLOCK : [
        12,
        5144,
        9544,
        17272,
        40100,
        611340,
        688260,
        708144,
        846220,
        1001856,
    ]
    OF_BLOCK_SIZE : [
        4868,
        1268,
        7716,
        22816,
        570400,
        76908,
        19872,
        138064,
        155624,
        19364,
    ]

Player:
    First Shop : 4599
    First ML Youth : 4599
    First ML Old : 4599
    First Unused : 4599

Club:
    Size : 92
    Max Abbr Name Size : 10
    First Emblem : 356
    First Club Emblem : 120
    J League Extra Teams : 54 # Only for J League games, for PES or WE set it to zero

Stadiums:
    Total : 59
    Max Lenght : 73

Leagues:
    Total : 39

Kits:
    Nation Kit Data Size : 0
    Club Kit Data Size : 552

Shop:
    Points Offset : 5216
    Has Background Selector : True
    Total Backgrounds : 63

NATIONS : [
    "Japan",
    "England",
    "France",
    "Italy",
    "Netherlands",
    "Spain",
    "Belgium",
    "Croatia",
    "Greece",
    "Portugal",
    "Russia",
    "Scotland",
    "Serbia",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "Argentina",
    "Brazil",
    "China",
    "Korea",
    "Australia",
    "Thailand",
    "Vietnam",
    "Iran",
    "Uzbekistan",
    "Iraq",
    "Kuwait",
    "Qatar",
    "Saudi Arabia",
    "Syria",
    "UAE",
    "Costa Rica",
    "Mexico",
    "United States",
    "New Zealand",
    "Papua New Guinea",
    "Nigeria",
    "South Africa",
    "Algeria",
    "Albania",
    "Andorra",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Bosnia-Herzegovina",
    "Bulgaria",
    "Cyprus",
    "Czech",
    "Denmark",
    "Estonia",
    "Faroe Islands",
    "Finland",
    "Georgia",
    "Germany",
    "Hungary",
    "Iceland",
    "Ireland",
    "Israel",
    "Kazakhstan",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Moldova",
    "Montenegro",
    "Northern Ireland",
    "Norway",
    "Poland",
    "Romania",
    "San Marino",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Wales",
    "Yugoslavia",
    "Angola",
    "Benin",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Cape Verde",
    "Chad",
    "Republic of the Congo",
    "Cote d'Ivoire",
    "Democratic Republic of the Congo",
    "Egypt",
    "Equatorial Guinea",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Liberia",
    "Libya",
    "Mali",
    "Morocco",
    "Mozambique",
    "Senegal",
    "Sierra Leone",
    "Togo",
    "Tunisia",
    "Zambia",
    "Zimbabwe",
    "Canada",
    "Grenada",
    "Guadeloupe",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Martinique",
    "Netherlands Antilles",
    "Panama",
    "Republic of Trinidad and Tobago",
    "Bolivia",
    "Chile",
    "Columbia",
    "Ecuador",
    "Paraguay",
    "Peru",
    "Uruguay",
    "Venezuela",
    "Bahrain",
    "Indonesia",
    "Malaysia",
    "north korea",
    "Oman",
    "Solomon Islands",
    "Free Nationality",
]